import type {
  Lesion,
  LesionAuditEvent,
  Patient,
} from "../types";

export const patientFixture: Patient = {
  id: 1,
  patient_code: "ED-0001",
  display_name: "Test patient",
  birth_year: null,
  notes: null,
  created_at: "2026-07-24T08:00:00Z",
  updated_at: "2026-07-24T08:00:00Z",
  mapped_lesions: 1,
  documented_lesions: 0,
  observation_count: 0,
  record_status: "needs_capture",
  highest_attention_level: null,
  attention_status: "not_assessed",
  last_activity_at: "2026-07-24T08:05:00Z",
  next_check_at: null,
};

export const lesionFixture: Lesion = {
  id: 7,
  patient_id: patientFixture.id,
  lesion_code: "L-0001",
  body_part: "chest",
  x: 0.1,
  y: 1.1,
  z: 0.3,
  label: "Baseline marker",
  notes: null,
  archived: false,
  created_at: "2026-07-24T08:05:00Z",
  observation_count: 0,
  accepted_observation_count: 0,
  latest_observation_at: null,
  latest_accepted_observation_id: null,
  latest_accepted_image_path: null,
  last_activity_at: "2026-07-24T08:05:00Z",
  attention_level: null,
  risk_status: "not_assessed",
  risk_score: null,
  risk_confidence: null,
  risk_assessed_at: null,
  risk_model_version: null,
  risk_validation_status: null,
  risk_domain_status: null,
  follow_up_action: "capture_required",
  next_check_at: null,
};

export const relocationEventFixture: LesionAuditEvent = {
  id: 3,
  lesion_id: lesionFixture.id,
  event_type: "location",
  previous_state: {
    body_part: "chest",
    x: 0.1,
    y: 1.1,
    z: 0.3,
    label: "Baseline marker",
    notes: null,
  },
  current_state: {
    body_part: "left-underarm",
    x: -0.63,
    y: 1.17,
    z: 0.2,
    label: "Axillary marker",
    notes: "Checked against the body map.",
  },
  change_reason: "Initial marker was too low.",
  created_at: "2026-07-24T09:00:00Z",
};
